# Generated by Django 5.0.14 on 2025-05-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douban_id', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('img', models.URLField()),
                ('href', models.URLField()),
                ('quote', models.TextField()),
                ('score', models.FloatField()),
                ('year', models.CharField(max_length=10)),
                ('countries', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
    ]
