# Generated by Django 5.2 on 2025-05-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyb',
            old_name='counter',
            new_name='content',
        ),
    ]
