# Generated by Django 5.2.1 on 2025-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyb', '0002_rename_counter_lyb_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
